[general]
error_reporting = false

[message]
log = false
report_custom_message = true
report_asset_materialization = true
report_asset_check = true
log_external_stream = false

[message_channel]
s3 = false
databricks = false
